import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { RuntimeSchema, SchemaBundle } from "@sembl/core";

/**
 * Serialize a RuntimeSchema to a TypeScript source string.
 */
function schemaToSource(schema: RuntimeSchema): string {
  const json = JSON.stringify(schema, null, 2);
  return `// Auto-generated by sembl extract — do not edit
import type { RuntimeSchema } from "@sembl/core";

export const ${schema.id}Schema: RuntimeSchema = ${json};
`;
}

/**
 * Emit a SchemaBundle as a set of individual .schema.ts files
 * plus a bundle index file.
 */
export function emitSchemas(bundle: SchemaBundle, outputDir: string): string[] {
  mkdirSync(outputDir, { recursive: true });

  const emittedFiles: string[] = [];
  const schemaIds: string[] = [];

  for (const [id, schema] of Object.entries(bundle.schemas)) {
    const fileName = `${id}.schema.ts`;
    const filePath = join(outputDir, fileName);
    writeFileSync(filePath, schemaToSource(schema), "utf-8");
    emittedFiles.push(filePath);
    schemaIds.push(id);
  }

  // Emit bundle index file
  const indexLines = [
    "// Auto-generated by sembl extract — do not edit",
    'import type { SchemaBundle } from "@sembl/core";',
    "",
  ];

  for (const id of schemaIds) {
    indexLines.push(`import { ${id}Schema } from "./${id}.schema.js";`);
  }

  indexLines.push("");
  indexLines.push("export const bundle: SchemaBundle = {");
  indexLines.push("  schemas: {");
  for (const id of schemaIds) {
    indexLines.push(`    ${id}: ${id}Schema,`);
  }
  indexLines.push("  },");
  indexLines.push("};");
  indexLines.push("");

  // Re-export individual schemas
  for (const id of schemaIds) {
    indexLines.push(`export { ${id}Schema } from "./${id}.schema.js";`);
  }
  indexLines.push("");

  const indexPath = join(outputDir, "index.ts");
  writeFileSync(indexPath, indexLines.join("\n"), "utf-8");
  emittedFiles.push(indexPath);

  return emittedFiles;
}
